#!/usr/bin/env bash
# Parses Apache log files in list format
# Groups visitors by IP and HTTP status code
# Displays the number of occurrences, IP, and the HTTP status
# + the code of each log, in a sorted order
# Task 103 done 

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
